import { ProductModel } from "./models/product.model";

const SAMPLE_PRODUCTS = [
  // ── WATCHES ────────────────────────────────────────────────────────────────
  {
    name: "Nautilus 5711/1A-014",
    brand: "Patek Philippe",
    category: "Watches",
    price: 145000,
    referenceNumber: "5711/1A-014",
    year: "2021",
    shortDescription: "The quintessential sports-luxury watch, in olive green dial.",
    description:
      "The Patek Philippe Nautilus in its most coveted iteration — the steel reference 5711 with an olive green dial. Designed by Gerald Genta in 1976, the Nautilus redefined the luxury sports watch category. This example presents in exceptional condition with box and papers, representing the final production year before the reference was discontinued.",
    craftsmanshipNotes:
      "The iconic porthole case profile is hand-polished with alternating satin and mirror finishes, a hallmark of Patek Philippe's mastery. The integrated bracelet required over 40 hours of hand-finishing per reference.",
    provenanceNotes: "Complete set with box, papers, and purchase receipt. Single-owner example.",
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=90",
      "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1200&q=90",
    condition: "Mint",
    tags: ["steel", "sports-luxury", "green-dial", "iconic"],
    specs: Object.fromEntries([
      ["Movement", "Caliber 26-330 S C"],
      ["Case Material", "Stainless Steel"],
      ["Case Diameter", "40 mm"],
      ["Water Resistance", "120 m"],
      ["Power Reserve", "45 hours"],
      ["Crystal", "Sapphire"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: false,
    isCertified: true,
    slug: "patek-philippe-nautilus-5711-1a-014",
  },
  {
    name: "Royal Oak 15500ST",
    brand: "Audemars Piguet",
    category: "Watches",
    price: 89500,
    referenceNumber: "15500ST.OO.1220ST.01",
    year: "2022",
    shortDescription: "The definitive Royal Oak — blue dial, steel, new generation movement.",
    description:
      "Audemars Piguet's Royal Oak reference 15500ST represents the pinnacle of the updated collection, housing the new Calibre 4302 with extended 70-hour power reserve. The blue \"Grande Tapisserie\" dial is unmistakably Royal Oak — each dial individually crafted at the Le Brassus manufacture.",
    craftsmanshipNotes:
      "The octagonal bezel is secured by eight hexagonal screws and alternates between polished and satin surfaces. Each Royal Oak case requires over 60 hours of individual hand-finishing.",
    provenanceNotes: "Complete set with original AP box and papers. Purchased from authorized dealer.",
    images: [
      "https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=800&q=90",
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=1200&q=90",
    condition: "Unworn",
    tags: ["steel", "blue-dial", "iconic", "sports-luxury"],
    specs: Object.fromEntries([
      ["Movement", "Calibre 4302"],
      ["Case Material", "Stainless Steel"],
      ["Case Diameter", "41 mm"],
      ["Water Resistance", "50 m"],
      ["Power Reserve", "70 hours"],
      ["Crystal", "Sapphire"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: true,
    isCertified: true,
    slug: "audemars-piguet-royal-oak-15500st",
  },
  {
    name: "RM 011 Felipe Massa",
    brand: "Richard Mille",
    category: "Watches",
    price: 195000,
    referenceNumber: "RM 011",
    year: "2019",
    shortDescription: "Richard Mille's iconic flyback chronograph — titanium and carbon.",
    description:
      "The Richard Mille RM 011 Felipe Massa Flyback Chronograph in titanium is a masterpiece of avant-garde watchmaking. Designed for Formula 1 race conditions, each RM 011 can withstand G-forces that would destroy conventional movements. The skeletonized dial reveals the movement architecture within — a philosophy of radical transparency.",
    craftsmanshipNotes:
      "The titanium tonneau case is hand-finished over 400 hours. The baseplate and bridges are machined from a single block of grade 5 titanium, then hand-anglaged with chamfers polished to mirror finish.",
    provenanceNotes: "Full set with box, papers, additional strap, and tools. Serviced 2023.",
    images: [
      "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800&q=90",
      "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=1200&q=90",
    condition: "Excellent",
    tags: ["titanium", "flyback", "chronograph", "limited"],
    specs: Object.fromEntries([
      ["Movement", "RMAC1 Manual Winding"],
      ["Case Material", "Titanium"],
      ["Case Dimensions", "50 × 40 mm"],
      ["Water Resistance", "50 m"],
      ["Power Reserve", "55 hours"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: false,
    isCertified: true,
    isLimitedEdition: true,
    slug: "richard-mille-rm-011-felipe-massa",
  },
  {
    name: "Submariner Date 126610LV",
    brand: "Rolex",
    category: "Watches",
    price: 22500,
    referenceNumber: "126610LV",
    year: "2023",
    shortDescription: "The green \"Hulk\" Submariner — Rolex's most iconic dive watch.",
    description:
      "The Rolex Submariner Date 126610LV, known as the \"Kermit\" in its updated generation, marries functional perfection with unmistakable presence. The green Cerachrom bezel insert and sunburst dial are water-resistant to 300 metres — engineered for serious diving, desired by discerning collectors.",
    craftsmanshipNotes:
      "The Oystersteel case and bracelet are finished with a combination of satin-brushed and polished surfaces. The green Cerachrom bezel insert is virtually scratchproof and impervious to UV radiation.",
    provenanceNotes: "Unworn with full set. Purchased December 2023 from authorised retailer.",
    images: [
      "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&q=90",
      "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=1200&q=90",
    condition: "Unworn",
    tags: ["steel", "green", "dive", "iconic"],
    specs: Object.fromEntries([
      ["Movement", "Calibre 3235"],
      ["Case Material", "Oystersteel"],
      ["Case Diameter", "41 mm"],
      ["Water Resistance", "300 m"],
      ["Power Reserve", "70 hours"],
      ["Crystal", "Sapphire with Cyclops"],
    ]),
    isAvailable: true,
    isFeatured: false,
    isNewArrival: true,
    isCertified: true,
    slug: "rolex-submariner-date-126610lv",
  },
  {
    name: "Lange 1 Moonphase",
    brand: "A. Lange & Söhne",
    category: "Watches",
    price: 52000,
    referenceNumber: "109.032",
    year: "2020",
    shortDescription: "German horological perfection — asymmetric dial, outsize date, moonphase.",
    description:
      "The A. Lange & Söhne Lange 1 Moonphase in white gold is a testament to German precision watchmaking at its zenith. The asymmetric dial arrangement — outsize date at 1 o'clock, moonphase at 7 — is instantly recognizable and entirely functional. The L901.5 manually wound movement is a work of art visible through the sapphire caseback.",
    craftsmanshipNotes:
      "The three-quarter plate made from untreated German silver is hand-engraved with Glashütte ribbing. Each gear is bevelled, polished, and finished by hand. The moonphase disc requires manual adjustment only once every 122.6 years.",
    provenanceNotes: "Full original set with inner and outer box, certificate, and spare buckle.",
    images: [
      "https://images.unsplash.com/photo-1584384539378-7e4d2baf51e2?w=800&q=90",
      "https://images.unsplash.com/photo-1527335480088-fd60d26f7c61?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1584384539378-7e4d2baf51e2?w=1200&q=90",
    condition: "Mint",
    tags: ["white-gold", "moonphase", "dress", "german"],
    specs: Object.fromEntries([
      ["Movement", "L901.5 Manual Winding"],
      ["Case Material", "White Gold"],
      ["Case Diameter", "38.5 mm"],
      ["Power Reserve", "72 hours"],
      ["Crystal", "Sapphire Anti-Reflective"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: false,
    isCertified: true,
    slug: "a-lange-sohne-lange-1-moonphase",
  },
  {
    name: "Daytona 116500LN",
    brand: "Rolex",
    category: "Watches",
    price: 38500,
    referenceNumber: "116500LN",
    year: "2021",
    shortDescription: "Steel Daytona with ceramic bezel — the ultimate sports chronograph.",
    description:
      "The Rolex Cosmograph Daytona 116500LN in Oystersteel with black ceramic bezel and white dial is the most sought-after chronograph on the market. The Calibre 4130 movement was entirely designed and developed in-house at Rolex, featuring a column wheel mechanism and vertical clutch for exceptional precision.",
    craftsmanshipNotes:
      "The black Cerachrom bezel's tachymeter scale is engraved and filled with platinum PVD. The pump-type pushers are machined from solid steel for lifetime durability.",
    provenanceNotes: "Complete set with box, papers, and hangtags. Purchased at Rolex boutique.",
    images: [
      "https://images.unsplash.com/photo-1625591341337-13be1a462d28?w=800&q=90",
      "https://images.unsplash.com/photo-1619946794135-5bc917a27793?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1625591341337-13be1a462d28?w=1200&q=90",
    condition: "Mint",
    tags: ["steel", "chronograph", "ceramic", "iconic"],
    specs: Object.fromEntries([
      ["Movement", "Calibre 4130"],
      ["Case Material", "Oystersteel"],
      ["Case Diameter", "40 mm"],
      ["Water Resistance", "100 m"],
      ["Power Reserve", "72 hours"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: false,
    isCertified: true,
    slug: "rolex-daytona-116500ln",
  },
  // ── WALLETS ────────────────────────────────────────────────────────────────
  {
    name: "Bearn Compact Wallet",
    brand: "Hermès",
    category: "Wallets",
    price: 1250,
    shortDescription: "Hermès' most iconic wallet silhouette — compact, refined, eternal.",
    description:
      "The Hermès Béarn Compact is the definitive luxury wallet for those who understand restraint. Crafted in Epsom calfskin — known for its fine grain, firmness, and light-scratching resistance — this compact version holds 6 cards and one bill section while maintaining a silhouette that slides effortlessly into a breast pocket.",
    craftsmanshipNotes:
      "Each Béarn is hand-stitched with Hermès' signature Sellier saddle stitch, using linen thread waxed by hand. The H closure clasp is cast in gold-plated brass and hand-polished. Every piece exits the Paris atelier after individual quality inspection.",
    provenanceNotes: "New in box with orange dust bag, ribbon, and certificate of authenticity.",
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=90",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=1200&q=90",
    condition: "Unworn",
    tags: ["epsom", "compact", "classic", "gold-hardware"],
    specs: Object.fromEntries([
      ["Material", "Epsom Calfskin"],
      ["Color", "Noir"],
      ["Hardware", "Gold-plated Brass"],
      ["Card Slots", "6"],
      ["Bill Compartment", "1"],
      ["Dimensions", "11 × 9 cm"],
    ]),
    isAvailable: true,
    isFeatured: true,
    isNewArrival: false,
    isCertified: true,
    slug: "hermes-bearn-compact-wallet",
  },
  {
    name: "Slender Wallet Taiga",
    brand: "Louis Vuitton",
    category: "Wallets",
    price: 690,
    shortDescription: "Understated LV — Taiga leather, no monogram, pure sophistication.",
    description:
      "Louis Vuitton's Slender Wallet in Taiga leather represents the house at its most understated. The dense grain of Taiga leather — originally developed for extreme Russian winters — is naturally water-resistant and exceptionally durable. Debossed with a subtle LV signature rather than the monogram canvas, this is the choice of those who know.",
    craftsmanshipNotes:
      "The interior is lined in leather throughout, with hand-painted edge finishing in contrasting colour. Bill compartment has no dividers, allowing the wallet to lay perfectly flat in any suit pocket.",
    provenanceNotes: "New with original LV box, dust bag, and care card.",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=90",
      "https://images.unsplash.com/photo-1624913503273-5f9c4e980dba?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=90",
    condition: "Unworn",
    tags: ["taiga", "slim", "leather", "understated"],
    specs: Object.fromEntries([
      ["Material", "Taiga Cowhide Leather"],
      ["Color", "Ardoise (Dark Grey)"],
      ["Card Slots", "6"],
      ["Bill Compartments", "2"],
      ["Dimensions", "11 × 9 × 1 cm"],
    ]),
    isAvailable: true,
    isFeatured: false,
    isNewArrival: true,
    isCertified: true,
    slug: "louis-vuitton-slender-wallet-taiga",
  },
  {
    name: "Intrecciato Bi-Fold Wallet",
    brand: "Bottega Veneta",
    category: "Wallets",
    price: 580,
    shortDescription: "The signature Intrecciato weave — Bottega at its most essential.",
    description:
      "Bottega Veneta's Intrecciato bi-fold wallet is the very definition of quiet luxury. The signature woven leather — each strip hand-cut and interlaced by Bottega's Maestra artisans in Vicenza — needs no logo. The matte nappa calfskin develops a gorgeous patina with use, telling the story of its owner.",
    craftsmanshipNotes:
      "The Intrecciato technique dates to 1966. Each wallet requires a single artisan to cut, weave, and stitch — a process that cannot be mechanized. The interior is lined in smooth calfskin with six card slots and a central bill section.",
    provenanceNotes: "New in original Bottega packaging with authenticity card.",
    images: [
      "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=800&q=90",
      "https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=1200&q=90",
    condition: "Unworn",
    tags: ["intrecciato", "woven", "nappa", "no-logo"],
    specs: Object.fromEntries([
      ["Material", "Nappa Calfskin"],
      ["Color", "Fondant (Dark Brown)"],
      ["Card Slots", "6"],
      ["Bill Compartments", "1"],
      ["Dimensions", "11 × 9.5 cm"],
    ]),
    isAvailable: true,
    isFeatured: false,
    isNewArrival: true,
    isCertified: true,
    slug: "bottega-veneta-intrecciato-bifold",
  },
  // ── CARD HOLDERS ────────────────────────────────────────────────────────────
  {
    name: "Simple Card Holder Calfskin",
    brand: "Hermès",
    category: "Card Holders",
    price: 350,
    shortDescription: "Four cards, zero excess. Hermès simplicity at its finest.",
    description:
      "The Hermès Simple Card Holder in smooth calfskin is the essential accessory for those who have perfected the art of travelling light. Four card slots, hand-painted edges, and the quiet confidence that comes from only carrying what is needed.",
    craftsmanshipNotes:
      "Smooth box calfskin — Hermès' most precisely treated leather — is used here, requiring minimal milling to achieve its characteristic firmness. Edge painted by hand in two coats.",
    provenanceNotes: "New in box with ribbon.",
    images: [
      "https://images.unsplash.com/photo-1603808033176-9d134e6f03e3?w=800&q=90",
    ],
    heroImage: "https://images.unsplash.com/photo-1603808033176-9d134e6f03e3?w=1200&q=90",
    condition: "Unworn",
    tags: ["compact", "minimalist", "calfskin"],
    specs: Object.fromEntries([
      ["Material", "Box Calfskin"],
      ["Color", "Noir"],
      ["Card Slots", "4"],
      ["Dimensions", "10 × 7 cm"],
    ]),
    isAvailable: true,
    isFeatured: false,
    isNewArrival: true,
    isCertified: true,
    slug: "hermes-simple-card-holder",
  },
];

export async function seedProducts() {
  const count = await ProductModel.countDocuments();
  if (count > 0) {
    return; // Already seeded
  }

  await ProductModel.insertMany(SAMPLE_PRODUCTS);
}
